# Generated by Django 4.1 on 2022-08-11 19:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Globalnet Bronze"),
                            (2, "Globalnet Silver"),
                            (3, "Globalnet Gold"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("companyName", models.CharField(max_length=100)),
                (
                    "comppanyEmail",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "primary_phone_number",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid", models.BooleanField(default=False)),
                ("assigned", models.BooleanField(default=False)),
                (
                    "plan",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Globalnet Bronze"),
                            (2, "Globalnet Silver"),
                            (3, "Globalnet Gold"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True, unique=True
                    ),
                ),
                ("phone_number", models.IntegerField(default=1000000000)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.today)),
                ("deadline", models.DateField(default=datetime.datetime.today)),
                ("amount", models.IntegerField(default=0)),
                ("trans_id", models.CharField(max_length=200)),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.customer",
                    ),
                ),
            ],
        ),
    ]
